include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy.gitlab-ci.yaml"

stages:
  - cloudbuild
  - deploy

cloudbuild:image:master:
  only:
    - master
  except:
    - tags
  extends: .cloudbuild:common

deploy:master:
  only:
    - master
  except:
    - tags
  extends: .deploy
  environment:
    name: stage
    on_stop: stop:master

stop:master:
  only:
    - master
  except:
    - tags
  extends: .stop
  environment:
    name: stage

cloudbuild:image:prod:
  only:
    - prod
  except:
    - tags
  extends: .cloudbuild:common

deploy:prod-green:
  only:
    - prod
  except:
    - tags
  extends: .deploy
  variables:
    APP_CONFIG: green
  environment:
    name: prod
    on_stop: stop:prod-green

stop:prod-green:
  only:
    - prod
  except:
    - tags
  extends: .stop
  variables:
    APP_CONFIG: green
  environment:
    name: prod

deploy:prod-blue:
  only:
    - prod
  except:
    - tags
  extends: .deploy
  variables:
    APP_CONFIG: blue
  environment:
    name: prod
    on_stop: stop:prod-blue

stop:prod-blue:
  only:
    - prod
  except:
    - tags
  extends: .stop
  variables:
    APP_CONFIG: blue
  environment:
    name: prod

deploy:prod-sahara-green:
  only:
    - prod
  except:
    - tags
  extends: .deploy
  variables:
    APP_CONFIG: sahara-green
  environment:
    name: prod
    on_stop: stop:prod-sahara-green

stop:prod-sahara-green:
  only:
    - prod
  except:
    - tags
  extends: .stop
  variables:
    APP_CONFIG: sahara-green
  environment:
    name: prod

deploy:prod-sahara-blue:
  only:
    - prod
  except:
    - tags
  extends: .deploy
  variables:
    APP_CONFIG: sahara-blue
  environment:
    name: prod
    on_stop: stop:prod-sahara-blue

stop:prod-sahara-blue:
  only:
    - prod
  except:
    - tags
  extends: .stop
  variables:
    APP_CONFIG: sahara-blue
  environment:
    name: prod
